### ISSUE TITLE
Issues authenticating with Facebook API

### ISSUE THREAD

**Issue by NoiSek** [lepture/flask-oauthlib#158]
I haven't been able to find any solutions from searching around, but building off of the example listed in the samples section for Facebook I consistently get an "Invalid response from Facebook" error.

Dumping the request seems to show that there is a very long token being returned to the callback along the lines of '?code=1234567890-abcdefghijklmnop', however actually trying to authenticate with the token fails. Possibly an API change? As far as I know Facebook is replying correctly, and similar code built off of the Twitter sample works perfectly fine.

A sample dump of the request args:

```
ImmutableMultiDict([('code', 'AQAPedwWavTb_cBx6NVy-qy3AL5YPr780oG5tA1LfITpVwkk-kr_4I0lG6B-vlhcYEubhuKhEM46bPs-1WpWUpJzcWfhkQ64lIkdLm9uSHSqeBHBM_6zw7SDpvVmGK-JKWBpAqRJuBKenl9zslQizthox96104iiul0uYQY67cmZgPXZi9uL-mcgZ5dRj387eKJIjNninBXxwCGgFkg5kLVHYt7t0ktUH58stYlxn2f98AXuSlrIvWsA5NeHsVbM8XY0XQrDrNbCvjDmEwHQGkZ3uZRbyaecN7MAi0bM0TrZzpuQ8j3M34DnQp_v9n4ktM4')])
```

I've created a gist of the relevant code I'm using just in case it's on my end, but having seen some similar issues could it be possible Oauthlib's implementation might have broken due to API changes?

https://gist.github.com/NoiSek/0262c460382dd830cdb3

**Comment by lepture** [comment]
@NoiSek Could you update facebook example if you have fixed it.

**Comment by rjaquino** [comment]
I hit this issue today using the example code. I'm going to try to uncover what the issue is, but if anyone happens to know, that'd be great.

**Comment by NoiSek** [comment]
Hey there, I solved this issue in a very hacky way which I would not recommend for production environments, but I eventually found the issue a few days after my last message.

When you ask Facebook for an access token, it does NOT give you an access token in the way you might expect. What I assumed to be a failure on Facebook's side was instead a (perhaps intentional) formatting error.

What you might expect:

` ` `http://mysite.com/callback?access_token=00000000000` ` ` 

or

` ` ` http://mysite.com/callback` ` `  with the access token passed as a POST argument in the headers. 

What *actuallly* happens is that Facebook responds like this:

` ` `http://mysite.com/callback?#access_token=0000000000` ` ` 
Because of this, it is -**impossible**- for any server side language to parse it, as the access token will now only be visible to the browser itself. It is not passed to the backend whatsoever.

My workaround was to set my callback within my Facebook API settings to http://mysite.com/translate instead of /callback, and parse it with Javascript:

` ` ` 
@app.route('/facebook/translate', methods=['GET'])
def facebook_translate():
  # Facebook responds with the access token as ?#access_token, 
  # rather than ?access_token, which is only accessible to the browser.
  # This part is where things get really, really dumb.
  return '''  <script type="text/javascript">
    var token = window.location.href.split("access_token=")[1]; 
    window.location = "/facebook/callback?access_token=" + token;
  </script> '''
` ` ` 

(Note: These are Flask routes)

I could then proceed as usual with this:

` ` ` 
@app.route('/facebook/callback', methods=['GET', 'POST'])
def facebook_callback():
  access_token = request.args.get("access_token")

  if access_token == "undefined":
    flash("You denied the request to sign in.", "error")
    return redirect(url_for('index'))

  graph = facebooksdk.GraphAPI(access_token)
  profile = graph.get_object("me")
` ` `

**Comment by rjaquino** [comment]
Thanks! I'm surprised this isn't run into more often.

**Comment by widnyana** [comment]
@NoiSek Nice

btw, I was curious. why do you use javascript redirect instead of flask's built in redirect?

**Comment by lepture** [comment]
I believe I've fixed the bug. https://github.com/lepture/flask-oauthlib/commit/2e5e1c4602124d854f88bb88fa5d888941f9ae0d

The documentation said (https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow/v2.2):

> To get an access token, make an HTTP GET request to the following OAuth endpoint

**Comment by NoiSek** [comment]
@widnyana The argument had to be parsed with Javascript, so once I returned a page to render I could no longer use Flask's redirect(). I do use it heavily otherwise.
