### ISSUE TITLE
Flask-OAuthlib and CORS headers

### ISSUE THREAD

**Issue by zgoda-mobica** [lepture/flask-oauthlib#161]
Need help debugging this issue.

I have OAuth2 endpoints implemented as suggested in docs, with token handler returning just None. Then if I set CORS headers using this snippet -> http://flask.pocoo.org/snippets/56/ I keep getting 400 Bad Request on both POST and OPTIONS request on this endpoint. I seem to be unable to debug this as this gets deep into oauthlib code and there I'm lost.

The order of decorators does not matter, in every case I get 400.

**Comment by lepture** [comment]
Don't use them on OAuth APIs.
