### ISSUE TITLE
Inconsistent config prefix OAUTHLIB vs OAUTH2

### ISSUE THREAD

**Issue by lnielsen** [lepture/flask-oauthlib#165]
``flask_oauthlib/contrib/cache.py`` uses ``OAUTHLIB`` as a config prefix, while ``bind_cache_grant`` uses ``OAUTH2`` and passes it down to ``flask_oauthlib/contrib/cache.py``. This can cause a bit of confusion :-)

Additionally I've noticed that ``OAUTHLIB_INSECURE_TRANSPORT`` exists, but all other config variables are prefixed with ``OAUTH2_``.

I would suggest using ``OAUTH2`` everywhere as prefix. I can submit a PR if you agree to that and make sure it's backward compatible.

See e.g.:
https://github.com/lepture/flask-oauthlib/blob/master/flask_oauthlib/contrib/oauth2.py#L66
https://github.com/lepture/flask-oauthlib/blob/master/flask_oauthlib/contrib/cache.py#L8

**Comment by lepture** [comment]
@lnielsen Thanks. There is no need for this change.
