### ISSUE TITLE
Is there a way to return user_id with access token

### ISSUE THREAD

**Issue by mikeywaites** [lepture/flask-oauthlib#167]
Hi,

I have poured over the source for a while now and I can't find a way to do this out of the box but basically what I was hoping to achieve was when `@oauth.token_hanlder` is called and extra credentials may be provided return the `user.id` for the user that has been authenticated.

It doesn't seem possible to get at the oauth.request object during a token grant and perhaps there is a good reason for this.

In any case it would be great if you could shed some light on this, it doesn't seem uncommon to get the users_id back with an access_token.

Also happy to provide a pull request if you have an approach for this?

**Comment by lepture** [comment]
@mikeywaites Actually, we can update the token here:

https://github.com/lepture/flask-oauthlib/blob/master/flask_oauthlib/provider/oauth2.py#L746

```
token['user_id'] = request.user.id
```

**Comment by CDA0** [comment]
So can this be set in the function decorated with @oauth.token_handler currently? or is a PR needed where you suggest @lepture ?

**Comment by lepture** [comment]
@CDA0 It is better to hook it in OAuthlib

**Comment by lepture** [comment]
Close it for now. It is better to hook it in OAuthlib.
