### ISSUE TITLE
Tests are not compatible with OAuth2 RFC

### ISSUE THREAD

**Issue by zgoda-mobica** [lepture/flask-oauthlib#168]
According to RFC, access token in authentication code flow may be requested only using POST HTTP method. Existing tests use GET to retrieve token and simple change in client and server (use POST as access token method in client and define both POST and GET as allowed methods in server) makes many OAuth2 tests to fail, including these testing authentication code.

See https://tools.ietf.org/html/rfc6749#section-4.1.3

**Comment by zgoda-mobica** [comment]
I'm sorry, that report was too early, i'm further investigating the issue.

**Comment by zgoda** [comment]
I made a pull request that solves this issue, I guess it's safe to close this issue.
