### ISSUE TITLE
Is there a way to return expires_in with access token

### ISSUE THREAD

**Issue by gaboelnuevo** [lepture/flask-oauthlib#170]
Hi, I'm interesting in return the expiration time of acces token in request token url
By example I try this:

@app.route('/oauth/token')
@oauth.token_handler
    return {'expire_in': 3600}

But this is not working, any idea?

**Comment by gaboelnuevo** [comment]
Apparently changing expires_in with another word is working

**Comment by lepture** [comment]
@gaboelnuevo you cannot change `expires_in`, it is built-in oauthlib. However, you can configure a `OAUTH2_PROVIDER_TOKEN_EXPIRES_IN` to change the default value.
