### ISSUE TITLE
Should extract_params capture `request.json` if applicable?

### ISSUE THREAD

**Issue by bartek** [lepture/flask-oauthlib#171]
Hi there,

I've currently implemented OAuth using a GET method, with query string parameters containing the various parameters needed to obtain a token. This works great, so thank you for that!

However, I've been trying to get the same result using a POST method, which I feel should be possible when requesting an OAuth Token (This is using `ResourceOwnerPasswordCredentialsGrant`)

When I try to send my OAuth request as a POST, with the parameters in the JSON body, it doesn't quite work. This is because `extract_params` only looks at `request.form`, where-as the JSON body is in `request.json`

I'm not familiar enough with OAuth to comment on if this is a good idea or not (I figure you guys can!), so I'd be curious to understand why this is not the case today.

At the moment, I can fix this on my own end by adjusting my providers `token_handler` to extract from the JSON body if it feels necessary, but if this is something that makes sense to go into this library .. all the better!

Cheers and thanks :-)

**Comment by lepture** [comment]
@bartek It is the RFC. Requesting a token should be in `application/x-www-form-urlencoded`

A Password Credentials Grant looks like:

            POST /oauth/token HTTP/1.1
            Host: server.example.com
            Authorization: Basic a-base64-token
            Content-Type: application/x-www-form-urlencoded

            grant_type=password&username={username}&password={password_string}

**Comment by bartek** [comment]
@lepture Thank you. If it's in the RFC, that makes sense. I did not even think to simply send an `application/x-www-form-urlencoded` POST request though!

**Comment by kfuchs** [comment]
Is it just me who feels that was just kind of thrown in there? Is there really a reason why it has to use `application/x-www-form-urlencoded`? Maybe to keep things simpler by not having to decode different types.

I personally feel like it's totally acceptable to implement the few additional lines, to simplify things.

**Comment by brettatoms** [comment]
Although using JSON for the request isn't configurable in flask-oauthlib you can work around it with: 

```
def json_to_form(f):
    @wraps(f)
    def _wrapper(*args, **kwargs):
        request.form = ImmutableMultiDict(request.json)
        return f(*args, **kwargs)
    return _wrapper


@blueprint.route('/oauth/token', methods=['POST'])
@json_to_form
@oauth2.token_handler
def access_token():
    return None
```
