### ISSUE TITLE
Is client.default_scopes ever used?

### ISSUE THREAD

**Issue by bigblind** [lepture/flask-oauthlib#182]
In the documentation, it says you can add a `default_scopes` property to your client model. I've searched through the source, but I can't find it being used anywhere. I'm currently adding all a client's default_scopes to a tokens when creating them, but is it being used somewhere else?

**Comment by lepture** [comment]
@bigblind https://github.com/lepture/flask-oauthlib/blob/f84a4ef73f230459cb949da2a687527ee4eef330/flask_oauthlib/provider/oauth2.py#L716
