### ISSUE TITLE
Scopes implying other scopes

### ISSUE THREAD

**Issue by bigblind** [lepture/flask-oauthlib#183]
A common practice for many authentication providers is to make one scope imply another. For instance, a `userinfo/private` could imply a `userinfo/public` scope.

One way this could be implemented, is by optionally passing yn `available_scopes` parameter to the Provider class, or provide it as a configuration value.

The value would be a dictionary, mapping from a scope to a list of scopes it implies. For instance

```Python
available_scopes = {
    "userinfo/private": ["userinfo/public"],
    "userinfo/pedit": ["userinfo/private"],
    "public": ["userinfo/public", "repos/public"],
    "repos/public": []
}

oauth = OAuth2Provider(app, available_scopes=available_scopes)
```
Now, when a call to verify_request is made, it can expand the request's scope, using a function like this, where `available_scopes` is a dictionary as described above, and `client_scopes` is a list of scopes the client has been granted:

```Python
def expand_scopes(available_scopes, client_scopes):
    all_scopes = set(client_scopes) # The set of all scopes the client has ben granted, after expansion.
    scopes_to_expand = list(client_scopes) # Scopes that still need to be expanded
    expanded = []    

    while len(scopes_to_expand) > 0:
        scope = scopes_to_expand.pop())
        if scope in expanded:
            continue
        implies = available_scopes[scope]
        all_scopes.update(implies)
        scopes_to_expand += implies
    
    return all_scopes
```

So given the `available_scopes` dictionary above:

```Python
>>> expand_scopes(available_scopes, ["public"])
set("public", "repos/public", "userinfo/public")
```

I haven't actually tested the above code, this is just for demonstrating the idea, but I'm willing to create a pull request for this, if you think this is a good idea. Other ways to implement this are welcome as well.

**Comment by lepture** [comment]
You can subclass `OAuth2Provider` and re-implement the `verify_request` method:

```python
class MyProvider(OAuth2Provider):
    def verify_request(self, scopes):
        scopes = expand_scopes(scopes):
        return super(MyProvider, self).verify_request(scopes)
```

**Comment by bigblind** [comment]
Oh, great idea!, thx.
