### ISSUE TITLE
How to implement client credentials flow

### ISSUE THREAD

**Issue by christophervalles** [lepture/flask-oauthlib#188]
Hi,

I've been looking into all the code and documentation trying to guess how to implement the client credentials flow without any success. I've done it before in other languages but I guess the "black magic" here of using OAuthLib is messing with my brain and I don't quite get it. 

Any example/documentation/help?

Thanks!

**Comment by lepture** [comment]
Hi @christophervalles , here is a little hint: https://github.com/lepture/flask-oauthlib/blob/master/tests/oauth2/test_oauth2.py#L340

**Comment by christophervalles** [comment]
Wow that was fast :)

Thanks, I'll look into that code (forgot to check the tests) :S

**Comment by psykidellic** [comment]
hey @christophervalles  did you get around to figuring this out?

**Comment by lepture** [comment]
Close it.

@psykidellic It's better to use [Authlib](https://github.com/lepture/authlib) now.

Here is the document for client credentials: https://docs.authlib.org/en/latest/flask/oauth2.html#client-credentials-grant
