### ISSUE TITLE
Ambiguous return by authorize_response

### ISSUE THREAD

**Issue by bostikforever** [lepture/flask-oauthlib#191]
Currently it seems that authorized_response can do one of three things:
1. Return a `None` value
2. Return an `OAuthException`
3. Return authorized response.

I am not quite sure about the motive for introducing 2 here: https://github.com/lepture/flask-oauthlib/commit/2d73e5edacd58e48a90dc0
Getting an exception object as response for an invalid grant is very surprising. Why not just propagate the exception?

**Comment by JonathonReinhart** [comment]
This is undocumented and seems completely broken.

+1 for propagating the exception.

@bostikforever Can you please edit your title and original post? The method is *authorize***d***_response*. 

The [sample code](http://flask-oauthlib.readthedocs.org/en/latest/client.html#oauth1-client) shows always using the non-`None` return value as a dictionary. And the [API documentation](http://flask-oauthlib.readthedocs.org/en/latest/api.html#flask_oauthlib.client.OAuthRemoteApp.authorized_response) has nothing at all to say about the return value.

**Comment by bostikforever** [comment]
Thanks, fixed.

**Comment by lepture** [comment]
Update client. Don't catch OAuthException now.

**Comment by JonathonReinhart** [comment]
Thanks @lepture! I'm curious when you expect a release to be put out with this change. I don't want to hurry you, I just want to know when I should expect to update my cod which uses this.

**Comment by lepture** [comment]
@JonathonReinhart probably next week.
