### ISSUE TITLE
authorized_response returns error for google example 

### ISSUE THREAD

**Issue by stanzheng** [lepture/flask-oauthlib#197]
The auth example for Google correctly authenticates and gets a valid auth token, however whenever 

https://github.com/lepture/flask-oauthlib/blob/master/example/google.py#L56

```
resp = google.authorized_response()
```

 is called it always returns _Invalid response from google_

do you have an idea as to why ? ive browsed over the docs and tried different different handlers but cant explain why returns always error.

Thank you

**Comment by mgoldsborough** [comment]
Same error here.  This is my authorization method.

```
@app.route('/auth/callback')
def authorized():
    print 'In authorized()'
    resp = google.authorized_response()

    print 'Printing response'
    print resp

    if resp is None:
        print 'Access denied.'
        return 'Access denied: reason=%s error=%s' % (
            request.args['error_reason'],
            request.args['error_description']
        )

    print 'Access granted!'

    session['google_token'] = (resp['access_token'], '')
    me = google.get('userinfo')
    return jsonify({'data': me.data})
```

The output is:

```
In authorized()
Printing response
Invalid response from google
```

Followed by a stack trace trying to access ```access_token``` on the ```resp``` object.

**Comment by stanzheng** [comment]
I noticed this happened after I had previously auth'ed a session previously. My best guess when it tried to ping the service again, it issued an invalid instead of actual auth tokens. I added some checks and worked around it than actually finding the root issue.

Maybe a user error than a lib error

**Comment by vl4dt** [comment]
Exact same error here.

**Comment by clyang** [comment]
Having the same issue. Hopefully it can be solved in the near future.

**Comment by ksripathi** [comment]
Hello stanzheng,

I have the same issue but got in different scenario.

Scenario :
I have two domains registered with google dashboard as redirected apis
 domain 1 : sub.domain1.com
 domain 2 : sub.domain2.com
both domain1 and domain2 are pointing to same public ip that mean domain2 is alias for domain1

Registered redirected apis with google dashborad :
 api1 : sub.domain1.com/authorized
 api2 : sub.domain2.com/authorized

I could successfully use google oauth service using flask-oauth library as expected with sub.domain1.com,
But,
If i use sub.domain2.com it is throwing error saying invalid response from google by redirecting into sub.domain1.com/authorized?code=somecode

Please suggest me how can I debug this

**Comment by stanzheng** [comment]
It's been a while since I looked at this but from what you're mentioning @ksripathi is a different issue from this and don't want to produce too much noise on this issue. 

You should consider filing a new issue for the maintainer but i would check if the `url_for` is passing in the correct subdomain before it goes to the auth page, it should say it in the URL after you get to the google login page. 


https://github.com/lepture/flask-oauthlib/blob/e3081a1db532efbf7f266152a9e4f8432b2f8bc8/example/google.py#L43-L45

I would check the values in here 

https://github.com/lepture/flask-oauthlib/blob/e3081a1db532efbf7f266152a9e4f8432b2f8bc8/example/google.py#L54-L56

Good luck I haven't used this lib in a while so I'm probably no help in the matter.

**Comment by kjabbe** [comment]
Any updates on this?

**Comment by lepture** [comment]
Please use https://github.com/lepture/authlib instead.

Here is an example on Google: https://github.com/authlib/playground
