### ISSUE TITLE
Use HTTP Basic Auth for client's access to token endpoint

### ISSUE THREAD

**Issue by emanueldima** [lepture/flask-oauthlib#199]
[Section 4.1.3](http://tools.ietf.org/html/rfc6749#section-4.1.3) says "If the client type is confidential or the client was issued client credentials (or assigned other authentication requirements), the client MUST authenticate with the authorization server as described in Section 3.2.1.", and that is HTTP Basic Authentication. 

This is the same issue as https://github.com/lepture/flask-oauthlib/issues/132. I don't understand the argument for closing that issue, please elaborate.

**Comment by frol** [comment]
@emanueldima Just for your info, I have just PRed a fix for this issue: #301.

**Comment by frol** [comment]
This issue is resolved with #301, which was merged last year, though there was no pypi release since then.
