### ISSUE TITLE
Error: [SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by youtux** [lepture/flask-oauthlib#200]
It seems that python (both 2.7.9 and 3.4.3) has problems with ssl cert verification with many hosts. In my project I have to make requests to `trakt.tv`, which seems to have a certificate not present in the python database.

You can replicate the bug just making a request to it:
```python
# Python 3
import urllib
trakttv = urllib.request.urlopen('https://trakt.tv')
```
which will raise a `urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>`

The same code with `https://www.google.com` works just fine. This is a big deal for `flask-oauthlib`, since it uses the python stdlib urllib/urllib2. Is there any workaround/fix?

EDIT: fixed typo in the example code

**Comment by ggold6** [comment]
SSL(3?) is becoming a big issue, i'm seeing this in API requests on api.github.com. 
Since Debian Jessie (8.0) came out this weekend, i've migrated to python 3.4.1, and am not seeing any more issues. Tried requests.get with your url, works fine. So does the github api.  And indeed, like you i tried an https request into google and it was fine earlier too, with 2.7.9, while github's API broke.
I really don't know of a fix, and can't see how flask-oauthlib can solve this issue. It's a python community thing. The whole PY2 vs PY3 is a huge issue. For example, flask-socketio doesn't work on PY3, since it relies on gevent, which doesn't support PY3(!). This whole SSL problem quickly escalated for me too. Little relief on your end; am writing to get as many people on board, initiating issues on the various libraries to get things moving.

I'd tell you to try downgrading to 3.7.1 just to see if this resolves your issues. I __know__ 2.7.9 has a bug working with SSL. But downgrading is a horrible solution to a problem.

**Comment by youtux** [comment]
Well, there is an alternative: it seems that the `requests` library solves this issue by using it's own `cacert.pem` certificate store.

Is that a viable option to rebuild this `flask-oauthlib` on top of  the `requests` library? If the answer is positive, I could start to work on this.

**Comment by lepture** [comment]
@youtux There is an experimental client in `contrib.client` https://github.com/lepture/flask-oauthlib/tree/master/flask_oauthlib/contrib/client which is using requests.

**Comment by lepture** [comment]
@youtux There is an experimental client in `contrib.client` https://github.com/lepture/flask-oauthlib/tree/master/flask_oauthlib/contrib/client which is using requests.

**Comment by youtux** [comment]
I have already seen that module, but I didn't find the `OAuth2Provider` class so I didn't bother too much. Now that I gave a better look I have found out that the equivalent for `OAuth2Provider` in the `contrib.client` package is the `OAuth2Application`!

Thank you for the tip.

**Comment by jacquesd** [comment]
I have the same problem (with OAuth1) and using the contrib client almost works.
The client relies on the `OAuth1Session` from `requests-oauthlib` which does a POST call in` _fetch_token` without the ability to pass any parameter such as the certificate to use for verification. (See [here](https://github.com/requests/requests-oauthlib/blob/master/requests_oauthlib/oauth1_session.py#L340)).
And while I did not  test it, it appears that the same problem is present with `OAuth2Session` (See [here](https://github.com/requests/requests-oauthlib/blob/master/requests_oauthlib/oauth2_session.py#L176))

Thankfully, lukasa over at `#python-requests` suggested a nice work around to specify the certificate. Requests uses `certifi` which we can mock to return the path to the certificate you need. My code looks like this:
```python
import sys

class FakeCertifi(object):
    def where(self):
        return '<path/to/your/cert.crt>'

sys.modules['certifi'] = FakeCertifi()
```
I will open an issue directly to `requests-oauthlib` and hopefully they will provide an option for the certificate's path. And then it would be great if Flask-OAuthlib could expose the option as well, at least in the contrib client.

**Comment by tonyseek** [comment]
@youtux Upgrading to Python 2.7.9 is an alternative way to resolve this issue. It has a new SSL module with SNI support.

**Comment by youtux** [comment]
@tonyseek I am already using Python 2.7.9 on Mac OS 10.10.3 (from homebrew)

**Comment by tonyseek** [comment]
It works on my local machine.

Python 2.7.9 (pyenv): 

``` python
>>> import urllib2
>>> r = urllib2.urlopen('https://trakt.tv')
>>> r.code
200
```

Python 3.4.2 (pyenv):

``` python
>>> import urllib
>>> r = urllib.request.urlopen('https://trakt.tv')
>>> r.code
200
```

**Comment by youtux** [comment]
Oh, you are right. Now it works for me too. Could it be that `trakt.tv` updated its certificate?
I suppose you can close this issue then.

**Comment by tonyseek** [comment]
> Could it be that trakt.tv updated its certificate?

You are right. I misled myself before. It is no possible to meet SNI caused hostname issue with `urllib`/`urllib2`.

- Python < 2.7.9 + `urllib`/`urllib2`: no SSL/TLS verifying.
- Python < 2.7.9 + `requests`: SSL/TLS verifying without SNI support. (e.g. `https://tonyseek.com` could not be verified here)
- Python 2.7.9 / Python 3.x + `urllib`/`urllib2`: SSL/TLS verifying with SNI support.
- Python 2.7.9 / Python 3.x + `requests`: SSL/TLS verifying with SNI support.
