### ISSUE TITLE
Non-expiring tokens?

### ISSUE THREAD

**Issue by OmeGak** [lepture/flask-oauthlib#208]
Is there a proper way of having non-expiring tokens with flask-oathlib? I just added this to my bearer token model so that it doesn't break anything while making it non-expiring, but I'd like to know if there's a better way.

```python
    @property
    def expires(self):
        # work around to have a non-expiring token
        return datetime.utcnow() + timedelta(days=3600)
```

**Comment by ThiefMaster** [comment]
The best solution would be allowing a `None` expires to prevent expiry. In that case, `expires_in` should be omitted (according to the RFC it's only recommended, not required).

**Comment by lepture** [comment]
expires is defined in OAuthlib. Currently it is impossible to set a None value for it.

**Comment by ThiefMaster** [comment]
So why not keep this open and open an issue for oauthlib to support non-expiring tokens?
