### ISSUE TITLE
Example of qq is broken in Python3

### ISSUE THREAD

**Issue by krrr** [lepture/flask-oauthlib#220]
If it's worthy to fix it, here is the detail:
`OAuthRemoteApp.get('/oauth2.0/me', ...).data` will be bytes object in Python3, so json_to_dict function fails.
The source of this bug: The weird API's body is `callback( {"client_id":"YOUR_APPID","openid":"YOUR_OPENID"} ); ` and the content-type is `text/html; charset=utf-8`.

**Comment by lepture** [comment]
@krrr I don't know anything about qq API. If you can fix it, a pull request is welcome.

**Comment by krrr** [comment]
OK, but I don't know how to deal with this kind of responce. Is there a way to let the flask-oauthlib handle encoding (content-type)? If not, then I have to decode it manually

**Comment by lepture** [comment]
Here are some examples:

1. https://github.com/lepture/flask-oauthlib/blob/master/example/weibo.py#L20
2. https://github.com/lepture/flask-oauthlib/blob/master/example/weibo.py#L64
