### ISSUE TITLE
Support OAuth 2.0 JWT Bearer Token Flow

### ISSUE THREAD

**Issue by probonopd** [lepture/flask-oauthlib#221]
As per http://tools.ietf.org/html/draft-ietf-oauth-jwt-bearer and http://tools.ietf.org/html/draft-jones-json-web-token - It was recently implemented in oauthlib, see https://github.com/idan/oauthlib/issues/50

**Comment by PeterParker** [comment]
Unfortunately it looks like only the _client_ has been implemented in `oauthlib` -- not the _server_.  The maintainer of that module is "accepting PR's"...

**Comment by JonathanHuot** [comment]
See howto implement it with the updated documentation section [oauthlib/Docs/Tokens/Bearer-JWT](https://oauthlib.readthedocs.io/en/latest/oauth2/tokens/bearer.html). Any comments are welcome
