### ISSUE TITLE
Contrib client timeline?

### ISSUE THREAD

**Issue by NJAldwin** [lepture/flask-oauthlib#224]
The [changelog for 0.9.0](https://flask-oauthlib.readthedocs.org/en/latest/changelog.html#version-0-9-0) states that the contrib client will become the official client in the future.  Is there a timeline for this change?

I'm looking to use some of the features of the contrib client (e.g. auto-refresh) but as it isn't really documented (especially not whether or not to use it over the original client), I'm hesitant.  Some clarification on this point would be much appreciated.

**Comment by lepture** [comment]
@NJAldwin You can use the contrib as you wish. I would keep it compatible when it is moved as the default client.
