### ISSUE TITLE
Example for outlook?

### ISSUE THREAD

**Issue by kramer65** [lepture/flask-oauthlib#231]
I am already using flask_oauthlib for google, facebook and Linkedin, which works like a charm.

I now also want to connect to outlook, but I'm having a hard time to get that to work. Does anybody have an example of how to do this using flask_oauthlib?

I tried the following:
```
from app import oauthManager
outlook = oauthManager.remote_app(
    'outlook',
    consumer_key='xxx',
    consumer_secret='xxx',
    request_token_params={},
    base_url='https://login.live.com/oauth20_authorize.srf',
    request_token_url=None,
    access_token_method='POST',
    access_token_url='https://login.live.com/oauth20_token.srf',
    authorize_url='https://login.live.com/oauth20_authorize.srf'
)

@app.route('/outlook')
def outlook():
    callback = url_for('.outlookback', _external=True)
    return outlook.authorize(callback=callback)
```
But I get an `AttributeError: 'function' object has no attribute 'authorize'`.

Any idea how I can authenticate users with Outlook?

**Comment by lepture** [comment]
I can't figure out what is wrong with your information.

**Comment by lepture** [comment]
No response. Close it.
