### ISSUE TITLE
Twitter Example Broken

### ISSUE THREAD

**Issue by 17twenty** [lepture/flask-oauthlib#276]
![blurred](https://cloud.githubusercontent.com/assets/379176/15884823/43e703b2-2d96-11e6-88c6-41bf1909ef44.png)

Checking out the latest version of the library doesn't work correctly when used with the examples/twitter.py

Did something break?

**Comment by widnyana** [comment]
@17twenty after a quick check, the app permission for writing a tweet doesn't satisfied.

I add a change, instead showing "Your tweet was too long", it will print out the error.
if you like it, I will send a PR, how do you think @lepture?

![twitter-sample](https://cloud.githubusercontent.com/assets/937158/16032251/3e83d8b8-322e-11e6-8faf-d819f0d56fe5.png)

**Comment by 17twenty** [comment]
Cool, LGTM.
