### ISSUE TITLE
Exceptions in provider/oauth2 are too general and handled badly

### ISSUE THREAD

**Issue by falquaddoomi** [lepture/flask-oauthlib#277]
This [recently-merged commit](https://github.com/lepture/flask-oauthlib/commit/0cabc05073daefbba126eb2c8f2004e4d2a561b7) adds exception handlers that catch Exception and just print out the error, with not even a traceback to help determine where the error is actually occurring.

Fixes: allow exceptions to percolate to the top, or at least provide the full exception and not just the (usually unhelpful) error message.

**Comment by lepture** [comment]
What if we format the message with `%r`?

**Comment by falquaddoomi** [comment]
I'd prefer for Exception just not to be handled at all. If you try it in
Flask, you'll notice that you get a nicely formatted error page with a
traceback without having to do any extra work. Plus, it lets the user of
the library decide how they want to handle those events if they choose.

**Comment by ThiefMaster** [comment]
Yeah, *any* kind of exception handling like this is somewhat awful. And if you do decide to swallow-and-log an exception, always use the `exception()` logger method since it includes the traceback.

**Comment by Sumukh** [comment]
This newer commit allows for the exception to be logged in it's entirety (which is so much better than the previous behavior of hiding the traceback) 

https://github.com/lepture/flask-oauthlib/commit/e1bb478b2015239dd12f1d3ee13fb2627a5a3407
