### ISSUE TITLE
Changing `default_token_placement`.

### ISSUE THREAD

**Issue by musically-ut** [lepture/flask-oauthlib#284]
StackOverflow's authentication API requires `access_token` to be [set as a query parameter](https://api.stackexchange.com/docs/authentication) instead of as a header to the request.

Is there a way of changing how the authentication token is added?

If not, I think the best way to solve the issue is to allow the user to set the `default_token_placement` while making the `oauthlib` client in `make_client` function. I would be tempted to add another parameter which configures the underlying client while creating the `remote_app`.

**Comment by ngokli** [comment]
I have this issue as well (with a different company's OAuth API).  What's the best way for me to pass the `access_token` as a query parameter?

**Comment by ngokli** [comment]
I suppose a quick, ugly hack would be to include the `access_token` directly in the url, so it would be in both the URL and the header.

I see authlib has `default_token_placement` control, but it sounds like it's still an alpha, and I've already (mostly) integrated with flask-oauthlib...

**Comment by lepture** [comment]
@ngokli please use https://github.com/lepture/authlib
