### ISSUE TITLE
Grant code is not completely validated

### ISSUE THREAD

**Issue by prateekmadhikar** [lepture/flask-oauthlib#286]
When the client exchanges their short lived token (grant code) for a long lived one (access token/refresh token), the grant code must be checked to ensure that it matches what the oauthlib had sent them.

Currently, this works:
**1. Get authorization code:**

```
POST oauth/authorize?client_id=valid_id
                     &response_type=code
                     &scope=all
```

Response:

``` json
{
    "code": "jWnNvGgIDSyfRhkTNSRCyRElR373ip"
}
```

**2. Exchange authorization code for an access token:**

```
POST oauth/token?client_id=valid_id
                 &client_secret=valid_secret
                 &grant_type=authorization_code
                 &redirect_url=oauth/redirect_uri
                 &code=INVALID_CODE_THAT_DOESNT_MATCH_THE_ONE_FROM_STEP_1
```

Response:

``` json
{
    "token_type": "Bearer",
    "version": "0.1.0",
    "access_token": "2Kz2MKZnCjXMJTbgcZyiJrxf8wP9kk",
    "scope": "all",
    "expires_in": 3600,
    "refresh_token": "lnN8cURwQhTJSWzMSiLh5DJFeTrqur"
}
```

Step 2 should fail with 

``` json
{
    "error": "invalid_grant"
}
```

since the code that was submitted in step 2 doesn't match the code in the response from step 1.

**Comment by night** [comment]
This is more likely an issue with your implementation rather than one with this library. You should be looking up authorization codes from storage and validating client_id against them. Check the docs: https://flask-oauthlib.readthedocs.io/en/latest/oauth2.html#grant-getter-and-setter

**Comment by prateekmadhikar** [comment]
About a year late, but yes it was an issue with our implementation!
