### ISSUE TITLE
idan/oauthlib 2.0 版本不兼容

### ISSUE THREAD

**Issue by wushuyi** [lepture/flask-oauthlib#296]
oauthlib 2.0 代码问题 :

``` python
request.scopes = None

if "openid" in request.scopes:
      handler = self.oidc_auth_grant

```

请锁定版本在 oauthlib==1.1.2

**Comment by wushuyi** [comment]
https://github.com/idan/oauthlib/blob/master/oauthlib/oauth2/rfc6749/endpoints/authorization.py#L110

https://github.com/idan/oauthlib/blob/master/oauthlib/oauth2/rfc6749/grant_types/openid_connect.py#L99

**Comment by Sumukh** [comment]
This PR should solve the issue. https://github.com/idan/oauthlib/pull/437
