### ISSUE TITLE
Returning data with the token handler

### ISSUE THREAD

**Issue by PavSidhu** [lepture/flask-oauthlib#307]
Using a password grant flow, along with the access and refresh token, I would like to return a User ID back to the client.
```
@views.route('/oauth/token', methods=['POST'])
@oauth.token_handler
def access_token(*args, **kwargs):
    return {
        'userID': 16
    }

```
There are no arguments passed to the function so I'm unsure as to how to check which User ID to pass through. If I had the Client ID or any of the tokens, I could do a check to find which user's it was. Would there be any method for doing this?

**Comment by lepture** [comment]
@PavSidhu That is impossible when I implemented this lib with OAuthlib. I haven't follow OAuthlib for a long time, maybe it is possible for now.

**Comment by authentik8** [comment]
In that case, should the docs for the [Request token handler](https://flask-oauthlib.readthedocs.io/en/latest/oauth2.html#token-handler) be updated?

**Comment by janakj** [comment]
You can do that in your @oauth.tokensetter. The first parameter to that function is a dictionary with various access token parameters that your token setter saves in the database. If you set your user id on that dictionary, it will be returned to the client, e.g.:

@oauth.tokensetter
def save_token(token, request, *args, **kwargs):
  ....
  token['user_id'] = 16

Note: remember that whatever you set on that dictionary must also be serializable into a URL query string, in case those parameters are returned to the client via a browser redirect.

**Comment by PavSidhu** [comment]
@janakj This is exactly what I wanted, thank you! I'll close the issue since the problem is solved.
