### ISSUE TITLE
security concerns over storing secrets in Flask's user session

### ISSUE THREAD

**Issue by miguelgrinberg** [lepture/flask-oauthlib#310]
A user was asking today a [question](https://www.reddit.com/r/flask/comments/5o5d0k/proper_way_of_handling_facebooktwitter_oauth/) on Reddit regarding the proper way to store OAuth access tokens. He uses this project, and was following the advice from this extension and its examples of storing the tokens obtained from providers in the Flask user session.

I was wondering if I'm missing something here, because those tokens will go out to clients as part of the session cookie and without any encryption, so they are potentially accessible to anyone who has access to the client computer.

Can you please comment on this practice?

**Comment by lepture** [comment]
The request token for OAuth1 is stored in session cookie, which will be invalid after requesting for an access token.

For OAuth 2, no token is saved in session cookies.

The examples are using session cookie to store tokens. But they are just examples, you should store tokens in your own db.

**Comment by miguelgrinberg** [comment]
I recommend that you change the examples to handle tokens securely. The problem is that most people is not well versed in security, so they will not know that the examples are doing this in an bad way.

**Comment by lepture** [comment]
@miguelgrinberg There is not a simple way to demo it. It would be too complex to add a DB for examples. We could add comments in the examples.

**Comment by mardix** [comment]
I think it's up to developer to actually know where to save the token. It could be in a RDBMS or NoSQL DB. 

These are just examples showing how to authenticate, get the token, etc; the rest is up to the developer.
