### ISSUE TITLE
Server application to server application Authentification using flask-oauthlib

### ISSUE THREAD

**Issue by pvagare** [lepture/flask-oauthlib#322]
Hi All,
I have two server applications. I want to authenticate that request coming from one server to other server is authenticated. here I don't want authenticate end user . I want to authenticate the applications. How should I achieve this flask-oauthlib. Please can you explain me ?

**Comment by ffleandro** [comment]
You have to use the grant type `client_credentials` flow.
Please read some more about [OAuth 2 here](https://aaronparecki.com/oauth-2-simplified/#other-app-types).

**Comment by pvagare** [comment]
@ffleandro thanks for reply. I will look into this.
