### ISSUE TITLE
Errors during client authorization using basic auth

### ISSUE THREAD

**Issue by mudge8i** [lepture/flask-oauthlib#337]
#301 Has broken our implementation when requiring a client authorization using basic auth.

2 things which I can see have changed which have caused issues for us.

1) request.client_id is now checked before the Authorization header.
https://github.com/lepture/flask-oauthlib/pull/301/files#diff-caa6a21372b10b235c8cf7e00402330bR603
It's possible that this attribute does not exist. We were getting 'Request' object has no attribute 'client_id'.

2) Comments here https://github.com/lepture/flask-oauthlib/pull/301/files#diff-caa6a21372b10b235c8cf7e00402330bR607 indicate that the extract_params helper will replace the Authorization header with a parsed dict but it doesn't appear to be doing so and instead returning None, None for the client.
With a valid Authorization header we were getting
flask_oauthlib: DEBUG: Authenticate client None
flask_oauthlib: DEBUG: Authenticate client failed, client not found.

If we are doing something wrong, would appreciate advice on the correct way to use authenticate_client

**Comment by lepture** [comment]
ping @frol

**Comment by frol** [comment]
@mudge8i I am digging into your problem.

1. I haven't had any issues with the code and `request.client_id` seemed to be always available.
2. What is in your `Authorization` header? It should be `Basic <base64-encoded-client_id:client_secret-string>`. If that is not the case, `None, None` is the correct output.

@lepture Thanks for pinging.

**Comment by frol** [comment]
1. Given oauthlib Request implementation, `client_id` and `client_secret` are always available on Request objects: https://github.com/idan/oauthlib/blob/master/oauthlib/common.py#L394-L395

    Please, provide the exact error you get in this regard.
2. Enable oauthlib DEBUG output and attach it here. If would be great if you can also provide the output of the `request.headers.get('Authorization')`.
3. Which OAuth2 Flow do you use?

Reading the code, I haven't revealed any issues; it should work fine.

**Comment by mudge8i** [comment]
@frol Thank you for looking at this and getting back to me.

I did some more looking (your link was very helpful), and I have discovered what was wrong.
The request object which was being passed into authenticate_client was not a oauthlib.common.Request but instead the default request from flask which surprisingly enough was working up until #301 was merged in.
