### ISSUE TITLE
Example for implicit grant flow. 

### ISSUE THREAD

**Issue by gsverma** [lepture/flask-oauthlib#339]
Hi,
I could use some help with implementation of provider/client for implicit grant flow. I have been trying this since 2 weeks now, without any luck. There are  many road blocks, I am beginning to feel that Flask-OAuthlib is biased towards grants with Auth code. 
If some one has managed to get implicit grant working with Flask-OAuthlib, I could really use one skeleton example, or at least some guideline on how to do it.

**Comment by superWeb** [comment]
Same problem here. 
I never see anywhere how to setup the Authorization Server for the Implicit Grant.
I just want to use a SPA Web Application to connect to the Flask AuthLib.
