### ISSUE TITLE
Unable to logout completely: authorized (for google) returning immediately (with success)

### ISSUE THREAD

**Issue by saptarshiguha** [lepture/flask-oauthlib#348]
Hello,
I;m using the latest flask-oathlib. Once i've clicked the logout link which runs the following code

```
@app.route('/logout')
def logout():
    session.pop('google_token', None)
    return "good bye"
```

I'm trying to log in again (hoping to reach the google login page so i can type my credentials) but

```
@app.route('/login')
def login():
    return google.authorize(callback=url_for('authorized', _external=True))
```

Having logged in once, the above code always returns successfully *without* landing on the google page.

How can I force the `google.authorize` to revisit the google login page (and make me type my credentials again)?

**Comment by saptarshiguha** [comment]
Solved. Do this


```
@app.route('/login')
def login():
    return google.authorize(callback=url_for('authorized', _external=True)
                            ,prompt='consent')
```

See "Prompting re-consent" from [https://developers.google.com/identity/protocols/OpenIDConnect?csw=1](google docs for oauth)

**Comment by rahulswimmer** [comment]
Ouath just makes the Google instance null, hence it  you out of Google. Now that's how the architecture is made. Logging out of Google, if you Logout of your app is a dirty work, but can't help if the requirement stipulates the same. Hence add the following to your signOut() function. My project was an Angular 6 app:

document.location.href = "https://www.google.com/accounts/Logout?continue=https://appengine.google.com/_ah/logout?continue=http://localhost:4200";

Here localhost:4200 is the URL of my app. If your login page is xyz.com then input that.

**Comment by o-x-y-g-e-n** [comment]
> Solved. Do this
> 
> ```
> @app.route('/login')
> def login():
>     return google.authorize(callback=url_for('authorized', _external=True)
>                             ,prompt='consent')
> ```
> 
> See "Prompting re-consent" from [https://developers.google.com/identity/protocols/OpenIDConnect?csw=1](google docs for oauth)

This didnt work for me. It said prompt is an unknown paramater.
google = oauth.remote_app('google',
                          base_url='https://www.google.com/accounts/',
                          authorize_url='https://accounts.google.com/o/oauth2/auth',
                          request_token_url=None,
                          request_token_params={'scope': 'https://www.googleapis.com/auth/userinfo.email',
                                                'response_type': 'code',
                                                 'prompt' : 'consent'},
                          access_token_url='https://accounts.google.com/o/oauth2/token',
                          access_token_method='POST',
                          access_token_params={'grant_type': 'authorization_code'},
                          consumer_key=GOOGLE_CLIENT_ID,
                          consumer_secret=GOOGLE_CLIENT_SECRET)
 
Paste it in the request_token_params.
