### ISSUE TITLE
How to revoke a token for google oauth?

### ISSUE THREAD

**Issue by saptarshiguha** [lepture/flask-oauthlib#349]
Hello,
Reading the google docs (https://developers.google.com/identity/protocols/OAuth2WebServer#callinganapi), it says i can revoke token (and thus force a login with credentials) by calling `credentials.revoke`.

What would be the flask-oathlib way to do this?

**Comment by eriknguyen** [comment]
Hi,

I think you can do it with [`revoke_token`](https://flask-oauthlib.readthedocs.io/en/latest/api.html#flask_oauthlib.provider.OAuth2RequestValidator.revoke_token).

Hope it helps!

**Comment by lepture** [comment]
@eriknguyen that is for provider.

@saptarshiguha just send a POST request as Google says.
