### ISSUE TITLE
Why running the FaceBook Example Error occurred?

### ISSUE THREAD

**Issue by JafferWilson** [lepture/flask-oauthlib#352]
I am getting this error after I ran the Facebook example from your repository. Kindly, help in understanding the problem.

![screenshot from 2017-09-22 16-46-05](https://user-images.githubusercontent.com/13446197/30742168-c958f78e-9f4c-11e7-95b8-6838e1f7468b.png)

**Comment by lepture** [comment]
Oh. If 127.0.0.1 is not working, try localhost.
