### ISSUE TITLE
No handlers could be found for logger "flask_oauthlib"

### ISSUE THREAD

**Issue by siengsotheara** [lepture/flask-oauthlib#359]
Hello all guy, I am a new pythoner. I am getting this error after I am tried to call method

@app.route('/oauth/authorize', methods=['GET', 'POST'])
@oauth.authorize_handler
def authorize(*args, **kwargs):

And I also get error message global name client id not defined 
Please help me!! Thanks

**Comment by frol** [comment]
"No handlers could be found for logger "flask_oauthlib"" - this means that you configured your logging weirdly, but it is just a warning, so even if you don't configure your logging correctly, OAuth will still work fine.

As to the "global name client_id not defined", you just do a really weird thing with OAuth, so I recommend you read about how OAuth 2 is supposed to work first and only then use this library.

**Comment by siengsotheara** [comment]
Ok, I see Thank you Sir @frol  but I have another question: Can I customize access_token string length to my own way? can you share me some example. because I see default is very short one

**Comment by frol** [comment]
You can (#42), just set `OAUTH2_PROVIDER_TOKEN_GENERATOR` in the config file pointing to the generator function you like (you can use either callable or a string pointing to the callable); the default one is [`random_token_generator`](https://github.com/idan/oauthlib/blob/433e1a1337f2a2a206da14636ef8e33158cd6895/oauthlib/oauth2/rfc6749/tokens.py#L213)

**Comment by siengsotheara** [comment]
@frol Ok OK I get it Very Thank big big Sir... :) Great deal
