### ISSUE TITLE
Contribution with SQLAlchemy model

### ISSUE THREAD

**Issue by lepture** [lepture/flask-oauthlib#36]
We can provide built-in models on Token and Client.

With this issue https://github.com/mitsuhiko/flask-sqlalchemy/issues/98 , we can create some plain SQLAlchemy models now.

**Comment by lepture** [comment]
Seems it will never happen.

**Comment by gawry** [comment]
Seems like it might happen in the near future. 

https://github.com/mitsuhiko/flask-sqlalchemy/pull/250
