### ISSUE TITLE
How can I separate resource server and authorization server in flask-oauthlib

### ISSUE THREAD

**Issue by b3g00d** [lepture/flask-oauthlib#362]
As [protected resource](https://flask-oauthlib.readthedocs.io/en/latest/oauth2.html#protect-resource) written, resource server and authorization server are one. How can I separate it?

**Comment by lepture** [comment]
@b3g00d thanks for your attention. Please take a look at https://github.com/lepture/authlib instead, which is well designed than Flask-OAuthlib. Version 0.3 will be ready before the end of this year, take a look at the documentation on OAuth 2 server:

https://docs.authlib.org/en/latest/flask/oauth2.html

**Comment by b3g00d** [comment]
@lepture It's good to hear that.
