### ISSUE TITLE
Validating response_type

### ISSUE THREAD

**Issue by p00h** [lepture/flask-oauthlib#366]
We do the check against response_type hardcoded list: `code` or `token`:
https://github.com/lepture/flask-oauthlib/blob/66220ee0830dd71d6d46e692368c2feffd41ed9b/flask_oauthlib/provider/oauth2.py#L937
This makes next check completely unusable:
https://github.com/lepture/flask-oauthlib/blob/66220ee0830dd71d6d46e692368c2feffd41ed9b/flask_oauthlib/provider/oauth2.py#L940

So, if im gonna use `id_token token` response_type, which does exist in valid response types list, this code is unreachable ever. Do I miss anything?
I have to implement ImplicitGrant flow, and could not get there yet.

**Comment by lepture** [comment]
@p00h for now, you can subclass `OAuth2RequestValidator` to re-implement this validate_response_type. Or, you can make a PR to fix this problem.

I'm working on another OAuth library, which will have built-in OpenID support. You might have an interest:

- Repo: https://github.com/lepture/authlib
- Docs: https://docs.authlib.org/
- Intro: https://lepture.com/en/2018/announcement-of-authlib

**Comment by p00h** [comment]
@lepture thank you, gonna take a look

**Comment by p00h** [comment]
@lepture, btw I cannot subclass `Oauth2RequestValidator` directly, because I'll have to rewrite lots of code: it is being instantiated inside your code.
