### ISSUE TITLE
extract_params() & Google Actions

### ISSUE THREAD

**Issue by robwilkes** [lepture/flask-oauthlib#369]
Hi,

I have Google Actions (Assistant) working with flask-oauthlib.
I can sign up no problem at all, however on the agent webhook API calls, they pass the access_token in the POST body.

I've been able to make it work by modifying extractparams() to include:
try:
	headers['Authorization'] = 'Bearer {}'.format(request.json.get('originalRequest').get('data').get('user').get('accessToken'))
except:
	pass

Is there a better, more elegant way to get this to work?
Is there a way I can override this behavior from within my app instead of modifying the flask-oauthlib package?

Additionally, the extracted body always seems to be None, with every OAuth request I've been able to send.

Thanks for all your help, this is a fantastic package.

**Comment by robwilkes** [comment]
I'm actually having to deal with Google Assistant and Alexa. They both use accessToken as the key, but provide is in different areas of the JSON payload.

I've come up with the following to parse the response and look for this value. I could have simply used multiple .get() functions but this should cater to more variations than simply Google or Alexa.

The code is ugly so i'm not submitting as a pull request, i'm sure there is a better way to do it.

```
def extract_params():
    """Extract request params."""

    uri = _get_uri_from_request(request)
    http_method = request.method
    headers = dict(request.headers)
    if 'wsgi.input' in headers:
        del headers['wsgi.input']
    if 'wsgi.errors' in headers:
        del headers['wsgi.errors']
    # Werkzeug, and subsequently Flask provide a safe Authorization header
    # parsing, so we just replace the Authorization header with the extraced
    # info if it was successfully parsed.
    if request.authorization:
        headers['Authorization'] = request.authorization

    if request.is_json:
        access_token = extract_access_token_from_json(request.json)
        if access_token:
            headers['Authorization'] = 'Bearer {}'.format(access_token)

    body = request.form.to_dict()
    return uri, http_method, body, headers

def extract_access_token_from_json(json):
    token_aliases = ['accessToken', 'access_token']
    for k, v in json.items():
        if k in token_aliases:
            return v
        if isinstance(v, dict):
            access_key = extract_access_token_from_json(v)
            if access_key:
                return access_key
    return None
```

**Comment by lepture** [comment]
@robwilkes Could you try https://github.com/lepture/authlib instead, which will be the replacement of this project.
