### ISSUE TITLE
Refresh tokens for client side.

### ISSUE THREAD

**Issue by evbots** [lepture/flask-oauthlib#88]
Hello,

I'm currently working with the coinbase API and they require refresh tokens. Implementing a refresh check on every request is a pain, since there is no "before_request" option for the client either.

Are there any plans to either: 

1. Allow before_request for client, not just the provider so that I can implement a refresh token expire check. OR
2. Integrate support for refresh tokens into the client code?

Thanks,

**Comment by NJAldwin** [comment]
Any chance this'll happen sometime in the future?

**Comment by lepture** [comment]
The contrib client has this feature.
